(function(){
  const data=VTStore.load(), query=new URLSearchParams(location.search), id=query.get("id"), stored=data.combos.find(c=>c.id===id), root=document.getElementById("comboContent");
  let shared=null;try{shared=JSON.parse(query.get("combo")||"null")}catch{}
  const combo=stored?.publico===false?null:(shared&&shared.id===id?shared:stored);
  const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  if(!combo||combo.publico===false){root.innerHTML='<div class="combo-notfound"><h1>Este combo no está disponible</h1><p>Puede que haya sido retirado o ya no esté publicado.</p><a class="btn btn-primary" href="combos.html">Ver combos disponibles</a></div>';return;}
  document.title=`${combo.nombre} | Virion Tec`;
  const unavailable=combo.activo===false;
  root.innerHTML=`<a class="back-link" href="combos.html">← Ver todos los combos</a><article class="combo-detail ${esc(combo.color)}"><div class="combo-detail-image">${VTMedia.element(combo.img,combo.nombre)}${unavailable?'<span class="unavailable-ribbon">No disponible actualmente</span>':''}</div><div class="combo-detail-copy"><span class="pill ${esc(combo.color)}">Combo Virion Tec</span><h1>${esc(combo.nombre)}</h1><p class="lead">${esc(combo.descripcion)}</p><strong class="combo-price">${esc(combo.precio)}</strong><h2>Este paquete incluye</h2><ul class="combo-includes">${(combo.incluye||[]).map(item=>`<li><span>+</span>${esc(item)}</li>`).join("")}</ul><details class="combo-requirements"><summary>Ver más · Requisitos</summary><ul>${(combo.requisitos||[]).map(item=>`<li>${esc(item)}</li>`).join("")||"<li>Consulta los requisitos por WhatsApp.</li>"}</ul></details>${unavailable?'<p class="unavailable-note">Este combo no está disponible actualmente. Escríbenos y te ayudamos a encontrar una alternativa.</p>':`<a class="btn btn-primary" href="https://wa.me/${encodeURIComponent(data.contacto.whatsapp)}?text=${encodeURIComponent(`¡Hola, Virion Tec! 👋 Me interesa el combo ${combo.nombre}. ¿Me comparten qué incluye, su precio final y disponibilidad? 😊`)}" target="_blank" rel="noopener">Consultar este combo por WhatsApp</a>`}<button class="btn btn-outline combo-share-detail" type="button">↗ Compartir este combo</button><small>La cotización final se confirma según el alcance y disponibilidad.</small></div></article>`;
  const toggle=document.getElementById("themeToggle");
  function apply(dark){document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("vt_theme",dark?"dark":"light");document.querySelectorAll(".brand img").forEach(img=>{const src=img.dataset.lightSrc||img.getAttribute("src");img.dataset.lightSrc=src.replace(/-b(?=\.png$)/,"");img.src=dark?img.dataset.lightSrc:img.dataset.lightSrc.replace(/\.png$/,"-b.png");});}
  apply(localStorage.getItem("vt_theme")==="dark");toggle.addEventListener("click",()=>apply(document.documentElement.dataset.theme!=="dark"));
  document.querySelector(".combo-share-detail")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(location.href);alert("¡Enlace copiado! Ya puedes compartir este combo 😊");}catch{prompt("Copia el enlace del combo:",location.href);}});
})();
